server:
  port: 1112
  
spring:
  application:
    name: hello-service

eureka:
  instance:
    hostname: peer2
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:1111/eureka