server:
  port: 1111

spring:
  application:
    name: hello-service

eureka:
  instance:
    hostname: peer1
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:1112/eureka