spring:
  application:
    name: trace-5
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
server:
  port: 9105
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka