server:
  port: 1113
  
spring:
  application:
    name: hello-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:1111/eureka,http://localhost:1112/eureka