spring:
  application:
    name: trace-7
  zipkin:
    base-url: http://localhost:9411/
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123456
server:
  port: 9107
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka