spring:
  application:
    name: trace-3
  zipkin:
    base-url: http://localhost:9411/   #zipkin有数据
server:
  port: 9103
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka