spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yang-lv-87/spring-cloud.git
          searchPaths: springcloudconfig/config-repo
          username: yang-lv-87
          password: 
      label: master
    
server:
  port: 7001
  
